apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: etherpad-app-placement
  namespace: etherpad-app
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            application-placement: etherpad-app
