apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - env:
        - name: DB_TYPE
          value: postgres
        - name: DB_URL
          value: 'postgresql://postgres:etherpad@database-1.cdgkeivikc1o.eu-west-1.rds.amazonaws.com:5432/etherpad?sslmode=require'
#        - name: DB_HOST
#          value: 'database-1.cdgkeivikc1o.eu-west-1.rds.amazonaws.com'
#        - name: DB_PORT
#          value: '5432'
#        - name: DB_DATABASE
#          value: 'etherpad?sslmode=allow'
#        - name: DB_USER
#          value: 'postgres'
#        - name: DB_PASS
#          value: 'etherpad'
        - name: NODE_ENV
          value: production
        image: etherpad/etherpad:2.3.2
#        command: ["/bin/bash"]
#        args:
#          - '-c'
#          - >-
#            set -eux &&
#            cp config/settings.json . &&
#            sed -i "s|DB_TYPE|${DB_TYPE}|" settings.json &&
#            sed -i '/DB_HOST/d' settings.json &&
#            sed -i '/DB_PORT/d' settings.json &&
#            sed -i '/DB_DATABASE/d' settings.json &&
#            sed -i '/DB_USER/d' settings.json &&
#            sed -i "s|.*DB_PASS.*| \"url\" : \"${DB_URL}\"|" settings.json &&
#            cat settings.json &&
#            ./src/bin/run.sh
        imagePullPolicy: Always
        name: etherpad
        ports:
        - containerPort: 9001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/etherpad/config
          name: etherpad-settings
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: etherpad-settings
        name: etherpad-settings
