apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
      - env:
        - name: DB_TYPE
          value: postgres
        - name: DB_URL
          value: 'postgresql://postgres:etherpad@database-1.ceblquvck1ro.us-east-1.rds.amazonaws.com:5432/etherpad?sslmode=allow'
#        - name: DB_HOST
#          value: ''
#        - name: DB_PORT
#          value: ''
#        - name: DB_DATABASE
#          value: ''
#        - name: DB_USER
#          value: ''
#        - name: DB_PASS
#          value: ''
        - name: NODE_ENV
          value: production
        image: quay.io/gpte-devops-automation/etherpad:latest
        command: ["/bin/bash"]
        args:
          - '-c'
          - >-
            set -eux &&
            cp config/settings.json . && 
            sed -i "s/DB_TYPE/${DB_TYPE}/" settings.json &&            
            sed -i "s/DB_URL/${DB_URL}/" settings.json &&            
            ./src/bin/run.sh
        imagePullPolicy: Always
        name: etherpad
        ports:
        - containerPort: 9001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/etherpad/config
          name: etherpad-settings
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: etherpad-settings
        name: etherpad-settings
